version: '3'

services:
  sistema-ventas:
    build: sistema-ventas
    ports:
      - "8080:8080"
    image: backend:1.0.1
    environment:
      DB_URL: jdbc:mysql://sistema-ventas-db:b:3306/facturacion_electronica?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      restaurante-database:
        condition: service_healthy
    networks:
        - spring-demo

  sistema-ventas-db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: facturacion_electronica
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
        - restaurante-volume:/var/lib/mysql
    networks:
        - spring-demo

  frontend-app:
    build: frontend-app
    image:  frontend:1.0.1
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - restaurante-app

networks:
  spring-demo:
    driver: bridge

volumes:
  restaurante-volume:
    driver: local

